#!/usr/bin/env python
# Copyright (c) 2014 Red Hat Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.
import json

from sahara import version

import sahara_helper
import swag


def main():
    app = sahara_helper.get_app()
    swagger = swag.from_flask(app, str(version.version_info))
    print(json.dumps(swagger, indent=2))


if __name__ == '__main__':
    main()
