#!/usr/bin/env python
import json
import pprint

import baker
from sahara import version

import sahara_helper
import swag


@baker.command
def all():
    app = sahara_helper.get_app()
    swagger = swag.from_flask(app, str(version.version_info))
    print(json.dumps(swagger, indent=2))


@baker.command
def paths():
    '''show all the paths.'''
    app = sahara_helper.get_app()
    swagger = swag.from_flask(app, str(version.version_info))
    paths = [p for p in swagger.get('paths',{}).keys() if not (p.endswith('.xml') or p.endswith('.json'))]
    pp = pprint.PrettyPrinter(indent=2)
    pp.pprint(sorted(paths))


baker.run()
