#!/usr/bin/env python
import json

from sahara import version

import sahara_helper
import swag


def main():
    app = sahara_helper.get_app()
    swagger = swag.from_flask(app, str(version.version_info))
    print(json.dumps(swagger, indent=2))


if __name__ == '__main__':
    main()
