#!/usr/bin/env python
import json
import pprint

import barbican.api.controllers.root
from barbican import version as version

from pecan_swagger import utils as swag


def main():
    pp = pprint.PrettyPrinter(indent=2)
    pp.pprint(swag.swagger_build('barbican', version.__version__))


if __name__ == '__main__':
    main()
